var h;h||=typeof Module != 'undefined' ? Module : {};var aa=[],ba="./this.program",ca=globalThis.document?.currentScript?.src,da="",ea;try{da=(new URL(".",ca)).href}catch{}ea=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var fa=console.log.bind(console),k=console.error.bind(console),m,q=!1,ha;
function t(a){h.onAbort?.(a);a=`Aborted(${a})`;k(a);q=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ia;async function ja(a){if(!m)try{var b=await ea(a);return new Uint8Array(b)}catch{}if(a==ia&&m)a=new Uint8Array(m);else throw"both async and sync fetching of the wasm failed";return a}async function ka(a,b){try{var c=await ja(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),t(d)}}
async function la(a){var b=ia;if(!m)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return ka(b,a)}class ma{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var u,v,na,w,y,z,oa,A,B,pa=a=>{for(;a.length>0;)a.shift()(h)},qa=[],ra=[],sa=()=>{var a=h.preRun.shift();ra.push(a)},C=0,ta=null,ua=!0;
function va(){t("missing function: $SOCKFS")}function wa(){t("missing function: $FS")}
var F=a=>{a=va.ue(a);if(!a)throw new wa.Xd(8);return a},xa=a=>{a=a.split(".");for(var b=0;b<4;b++){var c=Number(a[b]);if(isNaN(c))return null;a[b]=c}return(a[0]|a[1]<<8|a[2]<<16|a[3]<<24)>>>0},za=a=>{var b,c,d=[];if(!/^((?=.*::)(?!.*::.+::)(::)?([\dA-F]{1,4}:(:|\b)|){5}|([\dA-F]{1,4}:){6})((([\dA-F]{1,4}((?!\3)::|:\b|$))|(?!\2\3)){2}|(((2[0-4]|1\d|[1-9])?\d|25[0-5])\.?\b){4})$/i.test(a))return null;if(a==="::")return[0,0,0,0,0,0,0,0];a=a.startsWith("::")?a.replace("::","Z:"):a.replace("::",":Z:");
a.indexOf(".")>0?(a=a.replace(RegExp("[.]","g"),":"),a=a.split(":"),a[a.length-4]=Number(a[a.length-4])+Number(a[a.length-3])*256,a[a.length-3]=Number(a[a.length-2])+Number(a[a.length-1])*256,a=a.slice(0,a.length-2)):a=a.split(":");for(b=c=0;b<a.length;b++)if(typeof a[b]=="string")if(a[b]==="Z"){for(c=0;c<8-a.length+1;c++)d[b+c]=0;--c}else d[b+c]=ya(parseInt(a[b],16));else d[b+c]=a[b];return[d[1]<<16|d[0],d[3]<<16|d[2],d[5]<<16|d[4],d[7]<<16|d[6]]},Aa=(a,b,c,d,e)=>{switch(b){case 2:c=xa(c);B.fill(0,
a,a+16);e&&(v[e>>2]=16);u[a>>1]=b;v[a+4>>2]=c;u[a+2>>1]=ya(d);break;case 10:c=za(c),B.fill(0,a,a+28),e&&(v[e>>2]=28),v[a>>2]=b,v[a+8>>2]=c[0],v[a+12>>2]=c[1],v[a+16>>2]=c[2],v[a+20>>2]=c[3],u[a+2>>1]=ya(d)}},Ca=1,Da={},Ea={};function Fa(a){var b=xa(a);if(b!==null)return a;b=za(a);if(b!==null)return a;Da[a]?b=Da[a]:(b=Ca++,b="172.29."+(b&255)+"."+(b&65280),Ea[b]=a,Da[a]=b);return b}
var Ga=a=>(a&255)+"."+(a>>8&255)+"."+(a>>16&255)+"."+(a>>24&255),Ia=a=>{var b="",c,d=0,e=0,f=0,g=0;a=[a[0]&65535,a[0]>>16,a[1]&65535,a[1]>>16,a[2]&65535,a[2]>>16,a[3]&65535,a[3]>>16];var l=!0;for(c=0;c<5;c++)if(a[c]!==0){l=!1;break}if(l){c=Ga(a[6]|a[7]<<16);if(a[5]===-1)return"::ffff:"+c;if(a[5]===0)return c==="0.0.0.0"&&(c=""),c==="0.0.0.1"&&(c="1"),"::"+c}for(c=0;c<8;c++)a[c]===0&&(c-e>1&&(g=0),e=c,g++),g>d&&(d=g,f=c-d+1);for(c=0;c<8;c++)d>1&&a[c]===0&&c>=f&&c<f+d?c===f&&(b+=":",f===0&&(b+=":")):
(b+=Number(Ha(a[c]&65535)).toString(16),b+=c<7?":":"");return b},Ja=(a,b)=>{var c=u[a>>1],d=Ha(oa[a+2>>1]);switch(c){case 2:if(b!==16)return{md:28};a=v[a+4>>2];a=Ga(a);break;case 10:if(b!==28)return{md:28};a=[v[a+8>>2],v[a+12>>2],v[a+16>>2],v[a+20>>2]];a=Ia(a);break;default:return{md:5}}return{family:c,jd:a,port:d}},Ka=(a,b)=>{a=Ja(a,b);if(a.md)throw new wa.Xd(a.md);b=a.jd;a.jd=(Ea[b]?Ea[b]:null)||a.jd;return a},La=globalThis.TextDecoder&&new TextDecoder,G=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=
c);)++d;if(d-b>16&&a.buffer&&La)return La.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var f=a[b++]&63;if((e&224)==192)c+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=(e&240)==224?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;e<65536?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},Ma=0,Na={},Oa=a=>{if(!(a instanceof ma||a=="unwind"))throw a;},Pa=a=>{ha=a;ua||Ma>0||(h.onExit?.(a),q=!0);throw new ma(a);
},Qa=()=>{if(!(ua||Ma>0))try{var a=ha;ha=a;Pa(a)}catch(b){Oa(b)}},Ra=a=>{if(!q)try{a()}catch(b){Oa(b)}finally{Qa()}},$a=(a,b)=>{Sa=a;Ta=b;if(Ua)if(Va||=!0,a==0)H=function(){setTimeout(Wa,Math.max(0,Xa+b-performance.now())|0)};else if(a==1)H=function(){Ya(Wa)};else{if(!Za)if(globalThis.scheduler)Za=scheduler.postTask.bind(scheduler);else{var c=[];addEventListener("message",d=>{d.data==="setimmediate"&&(d.stopPropagation(),c.shift()())},!0);Za=d=>{c.push(d);postMessage("setimmediate","*")}}H=function(){Za(Wa)}}},
ib=(a,b,c,d,e)=>{function f(){return g<ab?(Qa(),!1):!0}Ua=a;bb=d;var g=ab;Va=!1;Wa=function(){if(!q)if(cb.length>0){var l=cb.shift();l.se(l.de);if(db){var n=db,p=n%1==0?n-1:Math.floor(n);db=l.ge?p:(8*n+(p+.5))/9}h.setStatus&&(l=h.statusMessage||"Please wait...",n=db??0,p=eb.oe??0,n?n<p?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(l):h.setStatus(""));f()&&setTimeout(Wa,0)}else if(f())if(fb=fb+1|0,Sa==1&&Ta>1&&fb%Ta!=0)H();else{Sa==0&&(Xa=performance.now());a:if(!q){for(l of gb)if(l()===
!1)break a;Ra(a);for(n of hb)n()}f()&&H()}};e||(b>0?$a(0,1E3/b):$a(1,1),H());if(c)throw"unwind";},Va=!1,H=null,ab=0,Ua=null,bb=0,Sa=0,Ta=0,fb=0,cb=[],gb=[],hb=[];function jb(){H=null;ab++}var kb=0;function Ya(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(kb===0)kb=b+1E3/60;else for(;b+2>=kb;)kb+=1E3/60;setTimeout(a,Math.max(kb-b,0))}}
var eb={},Xa,Wa,Za,db,lb=[0,document,window],I=a=>{a=a>2?a?G(B,a):"":a;return lb[a]||document.querySelector(a)},mb=a=>lb.indexOf(a)<0?a.getBoundingClientRect():{left:0,top:0},nb=[],J=a=>{var b=nb[a];b||(nb[a]=b=ob.get(a));return b};function pb(a){var b=K.ad[a];b.target.removeEventListener(b.$c,b.Kd,b.dd);K.ad.splice(a,1)}function qb(){if(navigator.userActivation?navigator.userActivation.isActive:K.wd&&K.Yd.td){var a=K.hd;K.hd=[];for(var b of a)b.zd(...b.Gd)}}
function L(a){if(!a.target)return-4;if(a.bd)a.Kd=function(c){++K.wd;K.Yd=a;qb();a.fd(c);qb();--K.wd},a.target.addEventListener(a.$c,a.Kd,a.dd),K.ad.push(a);else for(var b=0;b<K.ad.length;++b)K.ad[b].target==a.target&&K.ad[b].$c==a.$c&&pb(b--);return 0}function rb(a){return a==window?"#window":a==screen?"#screen":a?.nodeName??""}
var K={ee:0,te:0,xd:0,qd:0,Dd:0,Bd:0,ud:0,le:0,ze:0,ke:0,vd:0,yd:0,Ne:0,Ad:0,Ce(){for(;K.ad.length;)pb(K.ad.length-1);K.hd=[]},wd:0,hd:[],je(a,b,c){function d(f,g){if(f.length!=g.length)return!1;for(var l in f)if(f[l]!=g[l])return!1;return!0}for(var e of K.hd)if(e.zd==a&&d(e.Gd,c))return;K.hd.push({zd:a,Od:b,Gd:c});K.hd.sort((f,g)=>f.Od-g.Od)},Ee(a){K.hd=K.hd.filter(b=>b.zd!=a)},ad:[],De:(a,b)=>{for(var c=0;c<K.ad.length;++c)K.ad[c].target!=a||b&&b!=K.ad[c].$c||pb(c--)},Fe(a){var b=!1;for(let c=0;c<
K.ad.length;++c){let d=K.ad[c];d.target===a.target&&d.cd===a.cd&&d.bd===a.bd&&d.ed===a.ed&&(pb(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},M=(a,b,c)=>{var d=B;if(!(c>0))return 0;var e=b;c=b+c-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(g<=127){if(b>=c)break;d[b++]=g}else if(g<=2047){if(b+1>=c)break;d[b++]=192|g>>6;d[b++]=128|g&63}else if(g<=65535){if(b+2>=c)break;d[b++]=224|g>>12;d[b++]=128|g>>6&63;d[b++]=128|g&63}else{if(b+
3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63;d[b++]=128|g>>6&63;d[b++]=128|g&63;f++}}d[b]=0;return b-e},sb=(a,b,c,d,e,f)=>{K.ud||(K.ud=N(256));a={target:I(a),$c:f,cd:e,ed:b,bd:d,fd:g=>{var l=g.target.id??"",n=K.ud;M(rb(g.target),n+0,128);M(l,n+128,128);J(d)(e,n,b)&&g.preventDefault()},dd:c};return L(a)},tb=(a,b,c,d,e)=>{K.vd||(K.vd=N(276));return L({target:a,$c:e,cd:19,ed:b,bd:d,fd:f=>{var g=K.vd,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||
document.msFullscreenElement,n=!!l;w[g]=n;w[g+1]=K.fullscreenEnabled();var p=n?l:K.be,r=p?.id??"";M(rb(p),g+2,128);M(r,g+130,128);v[g+260>>2]=p?.clientWidth??0;v[g+264>>2]=p?.clientHeight??0;v[g+268>>2]=screen.width;v[g+272>>2]=screen.height;n&&(K.be=l);J(d)(19,g,b)&&f.preventDefault()},dd:c})},ub=(a,b,c,d,e,f)=>{K.xd||(K.xd=N(160));a={target:I(a),$c:f,cd:e,ed:b,bd:d,fd:g=>{var l=K.xd;z[l>>3]=g.timeStamp;var n=l>>2;v[n+2]=g.location;w[l+12]=g.ctrlKey;w[l+13]=g.shiftKey;w[l+14]=g.altKey;w[l+15]=g.metaKey;
w[l+16]=g.repeat;v[n+5]=g.charCode;v[n+6]=g.keyCode;v[n+7]=g.which;M(g.key??"",l+32,32);M(g.code??"",l+64,32);M(g.char??"",l+96,32);M(g.locale??"",l+128,32);J(d)(e,l,b)&&g.preventDefault()},dd:c};return L(a)},vb=(a,b,c)=>{z[a>>3]=b.timeStamp;var d=a>>2;v[d+2]=b.screenX;v[d+3]=b.screenY;v[d+4]=b.clientX;v[d+5]=b.clientY;w[a+24]=b.ctrlKey;w[a+25]=b.shiftKey;w[a+26]=b.altKey;w[a+27]=b.metaKey;u[d*2+14]=b.button;u[d*2+15]=b.buttons;v[d+8]=b.movementX;v[d+9]=b.movementY;a=mb(c);v[d+10]=b.clientX-(a.left|
0);v[d+11]=b.clientY-(a.top|0)},wb=(a,b,c,d,e,f)=>{K.qd||(K.qd=N(64));a=I(a);return L({target:a,td:f!="mousemove"&&f!="mouseenter"&&f!="mouseleave",$c:f,cd:e,ed:b,bd:d,fd:g=>{vb(K.qd,g,a);J(d)(e,K.qd,b)&&g.preventDefault()},dd:c})},xb=(a,b,c,d)=>{K.yd||(K.yd=N(257));return L({target:a,$c:"pointerlockchange",cd:20,ed:b,bd:d,fd:e=>{var f=K.yd,g=document.pointerLockElement;w[f]=!!g;var l=g?.id??"";M(rb(g),f+1,128);M(l,f+129,128);J(d)(20,f,b)&&e.preventDefault()},dd:c})},yb=(a,b,c,d)=>L({target:a,$c:"pointerlockerror",
cd:38,ed:b,bd:d,fd:e=>{J(d)(38,0,b)&&e.preventDefault()},dd:c}),zb=(a,b,c,d)=>{K.Bd||(K.Bd=N(36));a=I(a);return L({target:a,$c:"resize",cd:10,ed:b,bd:d,fd:e=>{if(e.target==a){var f=document.body;if(f){var g=K.Bd;v[g>>2]=0;v[g+4>>2]=f.clientWidth;v[g+8>>2]=f.clientHeight;v[g+12>>2]=innerWidth;v[g+16>>2]=innerHeight;v[g+20>>2]=outerWidth;v[g+24>>2]=outerHeight;v[g+28>>2]=pageXOffset|0;v[g+32>>2]=pageYOffset|0;J(d)(10,g,b)&&e.preventDefault()}}},dd:c})},Ab=(a,b,c,d,e,f)=>{K.Ad||(K.Ad=N(1552));a=I(a);
return L({target:a,td:f=="touchstart"||f=="touchend",$c:f,cd:e,ed:b,bd:d,fd:g=>{var l={},n=g.touches;for(var p of n)p.Ld=p.Nd=0,l[p.identifier]=p;for(var r of g.changedTouches)r.Ld=1,l[r.identifier]=r;for(var x of g.targetTouches)l[x.identifier].Nd=1;n=K.Ad;z[n>>3]=g.timeStamp;w[n+12]=g.ctrlKey;w[n+13]=g.shiftKey;w[n+14]=g.altKey;w[n+15]=g.metaKey;p=n+16;r=mb(a);x=0;for(let D of Object.values(l))if(l=p>>2,v[l]=D.identifier,v[l+1]=D.screenX,v[l+2]=D.screenY,v[l+3]=D.clientX,v[l+4]=D.clientY,v[l+5]=
D.pageX,v[l+6]=D.pageY,w[p+28]=D.Ld,w[p+29]=D.Nd,v[l+8]=D.clientX-(r.left|0),v[l+9]=D.clientY-(r.top|0),p+=48,++x>31)break;v[n+8>>2]=x;J(d)(e,n,b)&&g.preventDefault()},dd:c})},O,Bb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},Cb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&
(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Db=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Eb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return a.getSupportedExtensions()?.filter(c=>b.includes(c))??[]},Fb=1,P=[],Q=[],Gb=[],Hb=[],R=[],S=[],Ib=[],Jb=[],T=[],Kb={},Lb=4,Mb=0,Nb=a=>{for(var b=Fb++,c=a.length;c<b;c++)a[c]=null;return b},V=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=O[c](),g=f&&Nb(d);f?(f.name=g,d[g]=f):U||=1282;v[b+e*4>>2]=g}},Pb=(a,b)=>{a.Ed||(a.Ed=a.getContext,a.getContext=function(d,e){e=a.Ed(d,e);return d=="webgl"==e instanceof WebGLRenderingContext?e:null});var c=b.Md>1?a.getContext("webgl2",b):a.getContext("webgl",b);return c?
Ob(c,b):0},Ob=(a,b)=>{var c=Nb(Jb),d={handle:c,attributes:b,version:b.Md,Fd:a};a.canvas&&(a.canvas.ce=d);Jb[c]=d;if(typeof b.Jd=="undefined"||b.Jd)if((a=d)||(a=W),!a.ae){a.ae=!0;b=a.Fd;b.ye=b.getExtension("WEBGL_multi_draw");b.qe=b.getExtension("EXT_polygon_offset_clamp");b.pe=b.getExtension("EXT_clip_control");b.Oe=b.getExtension("WEBGL_polygon_mode");Bb(b);Cb(b);Db(b);b.me=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.we=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
a.version>=2&&(b.Id=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(a.version<2||!b.Id)b.Id=b.getExtension("EXT_disjoint_timer_query");for(var e of Eb(b))e.includes("lose_context")||e.includes("debug")||b.getExtension(e)}return c},U,W,Qb=(a,b,c,d,e,f)=>{a={target:I(a),$c:f,cd:e,ed:b,bd:d,fd:g=>{J(d)(e,0,b)&&g.preventDefault()},dd:c};L(a)},Rb=(a,b,c,d)=>{K.Dd||(K.Dd=N(96));return L({target:a,td:!0,$c:"wheel",cd:9,ed:b,bd:d,fd:e=>{var f=K.Dd;vb(f,e,a);z[f+64>>3]=e.deltaX;z[f+72>>3]=e.deltaY;z[f+
80>>3]=e.deltaZ;v[f+88>>2]=e.deltaMode;J(d)(9,f,b)&&e.preventDefault()},dd:c})},Sb=["default","low-power","high-performance"],Tb={},Vb=()=>{if(!Ub){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ba},b;for(b in Tb)Tb[b]===void 0?delete a[b]:a[b]=Tb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Ub=c}return Ub},Ub,Wb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);d<=127?b++:d<=2047?b+=
2:d>=55296&&d<=57343?(b+=4,++c):b+=3}return b},Xb=[null,[],[]],Yb=[],Zb=()=>{var a=Eb(O);return a=a.concat(a.map(b=>"GL_"+b))},$b=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=O.getParameter(34467);c=d?d.length:0;break;case 33309:if(W.version<2){U||=1282;return}c=Zb().length;break;case 33307:case 33308:if(W.version<2){U||=1280;return}c=a==33307?3:0}if(c===void 0)switch(d=O.getParameter(a),typeof d){case "number":c=d;break;
case "boolean":c=d?1:0;break;case "string":U||=1280;return;case "object":if(d===null)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:U||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)v[b+a*4>>2]=d[a];return}try{c=d.name|
0}catch(e){U||=1280;k(`GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:U||=1280;k(`GL_INVALID_ENUM in glGet0v: Native code calling glGet0v(${a}) and it returns ${d} of type ${typeof d}!`);return}v[b>>2]=c}else U||=1281},ac=a=>{var b=Wb(a)+1,c=N(b);c&&M(a,c,b);return c},bc=a=>a.slice(-1)=="]"&&a.lastIndexOf("["),cc=a=>{a-=5120;return a==0?w:a==1?B:a==2?u:a==4?v:a==6?y:a==5||a==28922||a==28520||a==30779||a==30782?A:oa},X=a=>{var b=
O.Zd;if(b){var c=b.ld[a];typeof c=="number"&&(b.ld[a]=c=O.getUniformLocation(b,b.Vd[a]+(c>0?`[${c}]`:"")));return c}U||=1282},Y=[],dc=[],ec=()=>a=>(crypto.getRandomValues(a),0),fc=a=>(fc=ec())(a),ic=a=>{var b=Wb(a)+1,c=hc(b);M(a,c,b);return c},lc=a=>{var b=jc();a();kc(b)};h.requestAnimationFrame=Ya;h.pauseMainLoop=jb;h.resumeMainLoop=function(){ab++;var a=Sa,b=Ta,c=Ua;Ua=null;ib(c,0,!1,bb,!0);$a(a,b);H()};h.preMainLoop&&gb.push(h.preMainLoop);h.postMainLoop&&hb.push(h.postMainLoop);
for(let a=0;a<32;++a)Yb.push(Array(a));for(var mc=new Float32Array(288),Z=0;Z<=288;++Z)Y[Z]=mc.subarray(0,Z);var nc=new Int32Array(288);for(Z=0;Z<=288;++Z)dc[Z]=nc.subarray(0,Z);h.noExitRuntime&&(ua=h.noExitRuntime);h.print&&(fa=h.print);h.printErr&&(k=h.printErr);h.wasmBinary&&(m=h.wasmBinary);h.arguments&&(aa=h.arguments);h.thisProgram&&(ba=h.thisProgram);if(h.preInit)for(typeof h.preInit=="function"&&(h.preInit=[h.preInit]);h.preInit.length>0;)h.preInit.shift()();
var oc,pc,qc,rc,sc,tc,uc,ya,Ha,vc,N,kc,hc,jc,wc,ob,xc={D:(a,b,c)=>{a=F(a);a=a.rd.accept(a);b&&Aa(b,a.family,Fa(a.ie),a.ne,c);return a.stream.re},Fa:(a,b,c)=>{F(a);Ka(b,c);return 0},L:()=>{},_a:()=>{},Ga:(a,b,c)=>{a=F(a);b=Ka(b,c);a.rd.connect(a,b.jd,b.port);return 0},Ma:()=>{},eb:()=>{},$a:()=>{},I:()=>{},Xa:()=>{},g:function(){return 0},Ta:()=>{},Ya:function(){},db:()=>{},jb:(a,b,c)=>{a=F(a);Aa(b,a.family,Fa(a.He||"0.0.0.0"),a.Le,c);return 0},N:function(){return 0},Ea:(a,b)=>{a=F(a);a.rd.ve(a,b);
return 0},Ra:()=>{},La:()=>{},Qa:()=>{},G:function(){},Ka:()=>{},F:()=>{},Ja:(a,b)=>{var c=F(a);a=A[b+8>>2];for(var d=v[b+12>>2],e=0,f=0;f<d;f++)e+=v[a+(8*f+4)>>2];e=c.rd.Be(c,e);if(!e)return 0;(f=A[b>>2])&&Aa(f,c.family,Fa(e.jd),e.port);b=0;c=e.buffer.byteLength;for(f=0;c>0&&f<d;f++){var g=v[a+(8*f+4)>>2];g&&(g=Math.min(g,c),B.set(e.buffer.subarray(b,b+g),A[a+8*f>>2]+b),b+=g,c-=g)}return b},Oa:()=>{},Ha:(a,b)=>{a=F(a);var c=A[b+8>>2],d=v[b+12>>2],e=A[b>>2];b=v[b+4>>2];if(e){var f=Ka(e,b);var g=f.port;
f=f.jd}for(e=b=0;e<d;e++)b+=v[c+(8*e+4)>>2];var l=new Uint8Array(b),n=0;for(e=0;e<d;e++)for(var p=A[c+8*e>>2],r=v[c+(8*e+4)>>2],x=0;x<r;x++)l[n++]=w[p+x];return a.rd.Ie(a,l,0,b,f,g)},O:()=>{},Sa:()=>{},Pa:()=>{},Na:()=>{},ab:()=>{},Bb:()=>t(""),Ab:()=>{ua=!1;Ma=0},bb:function(){return-52},cb:function(){},Cb:(a,b)=>{Na[a]&&(clearTimeout(Na[a].id),delete Na[a]);if(!b)return 0;var c=setTimeout(()=>{delete Na[a];Ra(()=>vc(a,performance.now()))},b);Na[a]={id:c,Me:b};return 0},gb:(a,b)=>{if(!(a>=0&&a<=
3))return 28;var c;a===0?c=1E6:c=1E3;na[b>>3]=BigInt(c);return 0},hb:function(a,b,c){if(!(a>=0&&a<=3))return 28;na[c>>3]=BigInt(Math.round((a===0?Date.now():performance.now())*1E3*1E3));return 0},ob:()=>{jb();Ua=null},Aa:()=>devicePixelRatio,H:(a,b,c)=>{a=I(a);if(!a)return-4;a=mb(a);z[b>>3]=a.width;z[c>>3]=a.height;return 0},r:()=>performance.now(),pb:()=>performance.now(),vb:(a,b)=>{function c(d){J(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},Ec:()=>{t("OOM")},S:(a,b,c,d)=>
sb(a,b,c,d,12,"blur"),xa:(a,b,c)=>{a=I(a);if(!a)return-4;a.width=b;a.height=c;return 0},T:(a,b,c,d)=>sb(a,b,c,d,13,"focus"),R:(a,b,c,d)=>{if(!K.fullscreenEnabled())return-1;a=I(a);if(!a)return-4;tb(a,b,c,d,"webkitfullscreenchange");return tb(a,b,c,d,"fullscreenchange")},aa:(a,b,c,d)=>ub(a,b,c,d,2,"keydown"),_:(a,b,c,d)=>ub(a,b,c,d,1,"keypress"),$:(a,b,c,d)=>ub(a,b,c,d,3,"keyup"),wb:(a,b,c)=>{a=J(a);ib(a,b,c)},ma:(a,b,c,d)=>wb(a,b,c,d,5,"mousedown"),fa:(a,b,c,d)=>wb(a,b,c,d,33,"mouseenter"),da:(a,
b,c,d)=>wb(a,b,c,d,34,"mouseleave"),ha:(a,b,c,d)=>wb(a,b,c,d,8,"mousemove"),ia:(a,b,c,d)=>wb(a,b,c,d,6,"mouseup"),V:(a,b,c,d)=>document.body?.requestPointerLock?(a=I(a))?xb(a,b,c,d):-4:-1,U:(a,b,c,d)=>document.body?.requestPointerLock?(a=I(a))?yb(a,b,c,d):-4:-1,E:(a,b,c,d)=>zb(a,b,c,d),W:(a,b,c,d)=>Ab(a,b,c,d,25,"touchcancel"),X:(a,b,c,d)=>Ab(a,b,c,d,23,"touchend"),Y:(a,b,c,d)=>Ab(a,b,c,d,24,"touchmove"),Z:(a,b,c,d)=>Ab(a,b,c,d,22,"touchstart"),Q:(a,b,c,d)=>{Qb(a,b,c,d,31,"webglcontextlost");return 0},
P:(a,b,c,d)=>{Qb(a,b,c,d,32,"webglcontextrestored");return 0},ba:(a,b,c,d)=>(a=I(a))?typeof a.onwheel!="undefined"?Rb(a,b,c,d):-1:-4,vc:(a,b)=>{var c=b>>2;b={alpha:!!w[b+0],depth:!!w[b+1],stencil:!!w[b+2],antialias:!!w[b+3],premultipliedAlpha:!!w[b+4],preserveDrawingBuffer:!!w[b+5],powerPreference:Sb[v[c+2]],failIfMajorPerformanceCaveat:!!w[b+12],Md:v[c+4],xe:v[c+5],Jd:w[b+24],$d:w[b+25],Ae:v[c+7],Ge:w[b+32]};a=I(a);return!a||b.$d?0:Pb(a,b)},oc:a=>{W=Jb[a];h.ctx=O=W?.Fd;return!a||O?0:-5},fb:(a,b)=>
{var c=0,d=0,e;for(e of Vb()){var f=b+c;A[a+d>>2]=f;c+=M(e,f,Infinity)+1;d+=4}return 0},Fc:(a,b)=>{var c=Vb();A[a>>2]=c.length;a=0;for(var d of c)a+=Wb(d)+1;A[b>>2]=a;return 0},q:()=>52,M:(a,b)=>{var c=0;if(a==0)c=2;else if(a==1||a==2)c=64;w[b]=2;u[b+2>>1]=1;na[b+8>>3]=BigInt(c);na[b+16>>3]=BigInt(0);return 0},J:function(){return 52},K:function(){return 52},Ia:()=>52,Va:function(){return 70},Wa:()=>52,Ua:(a,b,c,d)=>{for(var e=0,f=0;f<c;f++){var g=A[b>>2],l=A[b+4>>2];b+=8;for(var n=0;n<l;n++){var p=
a,r=B[g+n],x=Xb[p];r===0||r===10?((p===1?fa:k)(G(x)),x.length=0):x.push(r)}e+=l}A[d>>2]=e;return 0},kb:(a,b,c,d)=>{function e(x,D,zc,Ac,E,Bc){var Ba=x===10?28:16;E=x===10?Ia(E):Ga(E);Ba=N(Ba);Aa(Ba,x,E,Bc);E=N(32);v[E+4>>2]=x;v[E+8>>2]=D;v[E+12>>2]=zc;A[E+24>>2]=Ac;A[E+20>>2]=Ba;v[E+16>>2]=x===10?28:16;v[E+28>>2]=0;return E}var f=0,g=0,l=0,n=0,p=0,r=0;c&&(l=v[c>>2],n=v[c+4>>2],p=v[c+8>>2],r=v[c+12>>2]);p&&!r&&(r=p===2?17:6);!p&&r&&(p=r===17?2:1);r===0&&(r=6);p===0&&(p=1);if(!a&&!b)return-2;if(l&-1088||
c!==0&&v[c>>2]&2&&!a)return-1;if(l&32)return-2;if(p!==0&&p!==1&&p!==2)return-7;if(n!==0&&n!==2&&n!==10)return-6;if(b&&(b=b?G(B,b):"",g=parseInt(b,10),isNaN(g)))return l&1024?-2:-8;if(!a)return n===0&&(n=2),(l&1)===0&&(n===2?f=uc(2130706433):f=[0,0,0,uc(1)]),a=e(n,p,r,null,f,g),A[d>>2]=a,0;a=a?G(B,a):"";f=xa(a);if(f!==null)if(n===0||n===2)n=2;else if(n===10&&l&8)f=[0,0,uc(65535),f],n=10;else return-2;else if(f=za(a),f!==null)if(n===0||n===10)n=10;else return-2;if(f!=null)return a=e(n,p,r,a,f,g),A[d>>
2]=a,0;if(l&4)return-2;a=Fa(a);f=xa(a);n===0?n=2:n===10&&(f=[0,0,uc(65535),f]);a=e(n,p,r,null,f,g);A[d>>2]=a;return 0},u:a=>O.activeTexture(a),y:(a,b)=>{O.attachShader(Q[a],S[b])},b:(a,b)=>{a==35051?O.Hd=b:a==35052&&(O.kd=b);O.bindBuffer(a,P[b])},ga:(a,b,c)=>{O.bindBufferBase(a,b,P[c])},hc:(a,b,c,d,e)=>{O.bindBufferRange(a,b,P[c],d,e)},i:(a,b)=>{O.bindFramebuffer(a,Gb[b])},qc:(a,b)=>{O.bindRenderbuffer(a,Hb[b])},t:(a,b)=>{O.bindSampler(a,T[b])},h:(a,b)=>{O.bindTexture(a,R[b])},C:a=>{O.bindVertexArray(Ib[a])},
na:(a,b,c,d)=>O.blendColor(a,b,c,d),oa:(a,b)=>O.blendEquationSeparate(a,b),pa:(a,b,c,d)=>O.blendFuncSeparate(a,b,c,d),Qb:(a,b,c,d,e,f,g,l,n,p)=>O.blitFramebuffer(a,b,c,d,e,f,g,l,n,p),Bc:(a,b,c,d)=>{W.version>=2?c&&b?O.bufferData(a,B,d,c,b):O.bufferData(a,b,d):O.bufferData(a,c?B.subarray(c,c+b):b,d)},z:(a,b,c,d)=>{var e=B;W.version>=2?c&&O.bufferSubData(a,b,e,d,c):O.bufferSubData(a,b,e.subarray(d,d+c))},Db:a=>O.checkFramebufferStatus(a),lc:(a,b,c,d)=>O.clearBufferfi(a,b,c,d),ra:(a,b,c)=>{O.clearBufferfv(a,
b,y,c>>2)},kc:(a,b,c)=>{O.clearBufferiv(a,b,v,c>>2)},l:(a,b,c,d)=>{O.colorMask(!!a,!!b,!!c,!!d)},Fb:a=>{O.compileShader(S[a])},Lb:(a,b,c,d,e,f,g,l,n)=>{W.version>=2?O.kd||!l?O.compressedTexSubImage2D(a,b,c,d,e,f,g,l,n):O.compressedTexSubImage2D(a,b,c,d,e,f,g,B,n,l):O.compressedTexSubImage2D(a,b,c,d,e,f,g,B.subarray(n,n+l))},Jb:(a,b,c,d,e,f,g,l,n,p,r)=>{O.kd?O.compressedTexSubImage3D(a,b,c,d,e,f,g,l,n,p,r):O.compressedTexSubImage3D(a,b,c,d,e,f,g,l,n,B,r,p)},wc:()=>{var a=Nb(Q),b=O.createProgram();
b.name=a;b.pd=b.nd=b.od=0;b.Cd=1;Q[a]=b;return a},Hb:a=>{var b=Nb(S);S[b]=O.createShader(a);return b},la:a=>O.cullFace(a),Mb:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+c*4>>2],e=P[d];e&&(O.deleteBuffer(e),e.name=0,P[d]=null,d==O.Hd&&(O.Hd=0),d==O.kd&&(O.kd=0))}},A:(a,b)=>{for(var c=0;c<a;++c){var d=v[b+c*4>>2],e=Gb[d];e&&(O.deleteFramebuffer(e),e.name=0,Gb[d]=null)}},o:a=>{if(a){var b=Q[a];b?(O.deleteProgram(b),b.name=0,Q[a]=null):U||=1281}},ya:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+c*4>>2],e=Hb[d];e&&
(O.deleteRenderbuffer(e),e.name=0,Hb[d]=null)}},za:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+c*4>>2],e=T[d];e&&(O.deleteSampler(e),e.name=0,T[d]=null)}},m:a=>{if(a){var b=S[a];b?(O.deleteShader(b),S[a]=null):U||=1281}},k:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+c*4>>2],e=R[d];e&&(O.deleteTexture(e),e.name=0,R[d]=null)}},Dc:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+c*4>>2];O.deleteVertexArray(Ib[d]);Ib[d]=null}},v:a=>O.depthFunc(a),w:a=>{O.depthMask(!!a)},c:a=>O.disable(a),ja:a=>{O.disableVertexAttribArray(a)},
Sb:(a,b,c)=>{O.drawArrays(a,b,c)},Tb:(a,b,c,d)=>{O.drawArraysInstanced(a,b,c,d)},sa:(a,b)=>{for(var c=Yb[a],d=0;d<a;d++)c[d]=v[b+d*4>>2];O.drawBuffers(c)},Ub:(a,b,c,d)=>{O.drawElements(a,b,c,d)},Vb:(a,b,c,d,e)=>{O.drawElementsInstanced(a,b,c,d,e)},f:a=>O.enable(a),dc:a=>{O.enableVertexAttribArray(a)},j:(a,b,c,d)=>{O.framebufferRenderbuffer(a,b,c,Hb[d])},d:(a,b,c,d,e)=>{O.framebufferTexture2D(a,b,c,R[d],e)},x:(a,b,c,d,e)=>{O.framebufferTextureLayer(a,b,R[c],d,e)},ka:a=>O.frontFace(a),Cc:(a,b)=>{V(a,
b,"createBuffer",P)},B:(a,b)=>{V(a,b,"createFramebuffer",Gb)},rc:(a,b)=>{V(a,b,"createRenderbuffer",Hb)},xc:(a,b)=>{V(a,b,"createSampler",T)},Ac:(a,b)=>{V(a,b,"createTexture",R)},Ca:(a,b)=>{V(a,b,"createVertexArray",Ib)},sc:(a,b)=>O.getAttribLocation(Q[a],b?G(B,b):""),a:(a,b)=>$b(a,b),uc:(a,b,c,d)=>{a=O.getProgramInfoLog(Q[a]);a===null&&(a="(unknown error)");b=b>0&&d?M(a,d,b):0;c&&(v[c>>2]=b)},ua:(a,b,c)=>{if(c)if(a>=Fb)U||=1281;else if(a=Q[a],b==35716)a=O.getProgramInfoLog(a),a===null&&(a="(unknown error)"),
v[c>>2]=a.length+1;else if(b==35719){if(!a.pd){var d=O.getProgramParameter(a,35718);for(b=0;b<d;++b)a.pd=Math.max(a.pd,O.getActiveUniform(a,b).name.length+1)}v[c>>2]=a.pd}else if(b==35722){if(!a.nd)for(d=O.getProgramParameter(a,35721),b=0;b<d;++b)a.nd=Math.max(a.nd,O.getActiveAttrib(a,b).name.length+1);v[c>>2]=a.nd}else if(b==35381){if(!a.od)for(d=O.getProgramParameter(a,35382),b=0;b<d;++b)a.od=Math.max(a.od,O.getActiveUniformBlockName(a,b).length+1);v[c>>2]=a.od}else v[c>>2]=O.getProgramParameter(a,
b);else U||=1281},Eb:(a,b,c,d)=>{a=O.getShaderInfoLog(S[a]);a===null&&(a="(unknown error)");b=b>0&&d?M(a,d,b):0;c&&(v[c>>2]=b)},ea:(a,b,c)=>{c?b==35716?(a=O.getShaderInfoLog(S[a]),a===null&&(a="(unknown error)"),v[c>>2]=a?a.length+1:0):b==35720?(a=O.getShaderSource(S[a]),v[c>>2]=a?a.length+1:0):v[c>>2]=O.getShaderParameter(S[a],b):U||=1281},Da:(a,b)=>{if(W.version<2)return U||=1282,0;var c=Kb[a];if(c)return b<0||b>=c.length?(U||=1281,0):c[b];switch(a){case 7939:return c=Zb().map(ac),c=Kb[a]=c,b<0||
b>=c.length?(U||=1281,0):c[b];default:return U||=1280,0}},ta:(a,b)=>{b=b?G(B,b):"";if(a=Q[a]){var c=a,d=c.ld,e=c.Wd,f;if(!d){c.ld=d={};c.Vd={};var g=O.getProgramParameter(c,35718);for(f=0;f<g;++f){var l=O.getActiveUniform(c,f);var n=l.name;l=l.size;var p=bc(n);p=p>0?n.slice(0,p):n;var r=c.Cd;c.Cd+=l;e[p]=[l,r];for(n=0;n<l;++n)d[r]=n,c.Vd[r++]=p}}c=a.ld;d=0;e=b;f=bc(b);f>0&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.Wd[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||O.getUniformLocation(a,b)))return d}else U||=
1281;return-1},Pb:(a,b,c)=>{for(var d=Yb[b],e=0;e<b;e++)d[e]=v[c+e*4>>2];O.invalidateFramebuffer(a,d)},va:a=>{a=Q[a];O.linkProgram(a);a.ld=0;a.Wd={}},Ba:(a,b)=>{a==3317?Lb=b:a==3314&&(Mb=b);O.pixelStorei(a,b)},qa:(a,b)=>O.polygonOffset(a,b),Rb:a=>O.readBuffer(a),pc:(a,b,c,d,e)=>O.renderbufferStorageMultisample(a,b,c,d,e),wa:(a,b,c)=>{O.samplerParameterf(T[a],b,c)},e:(a,b,c)=>{O.samplerParameteri(T[a],b,c)},mc:(a,b,c,d)=>O.scissor(a,b,c,d),Gb:(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var g=(g=A[c+f*4>>
2])?G(B,g,d?A[d+f*4>>2]:void 0):"";e+=g}O.shaderSource(S[a],e)},Ob:(a,b,c)=>O.stencilFunc(a,b,c),jc:(a,b,c,d)=>O.stencilFuncSeparate(a,b,c,d),n:a=>O.stencilMask(a),Nb:(a,b,c)=>O.stencilOp(a,b,c),ic:(a,b,c,d)=>O.stencilOpSeparate(a,b,c,d),zc:(a,b,c,d,e)=>O.texStorage2D(a,b,c,d,e),yc:(a,b,c,d,e,f)=>O.texStorage3D(a,b,c,d,e,f),Kb:(a,b,c,d,e,f,g,l,n)=>{if(W.version>=2){if(O.kd){O.texSubImage2D(a,b,c,d,e,f,g,l,n);return}if(n){var p=cc(l);O.texSubImage2D(a,b,c,d,e,f,g,l,p,n>>>31-Math.clz32(p.BYTES_PER_ELEMENT));
return}}if(n){p=cc(l);var r=f*(({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[g-6402]||1)*p.BYTES_PER_ELEMENT*(Mb||e)+Lb-1&-Lb);n=p.subarray(n>>>31-Math.clz32(p.BYTES_PER_ELEMENT),n+r>>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else n=null;O.texSubImage2D(a,b,c,d,e,f,g,l,n)},Ib:(a,b,c,d,e,f,g,l,n,p,r)=>{if(O.kd)O.texSubImage3D(a,b,c,d,e,f,g,l,n,p,r);else if(r){var x=cc(p);O.texSubImage3D(a,b,c,d,e,f,g,l,n,p,x,r>>>31-Math.clz32(x.BYTES_PER_ELEMENT))}else O.texSubImage3D(a,b,c,d,e,f,g,l,n,
p,null)},cc:(a,b,c)=>{if(W.version>=2)b&&O.uniform1fv(X(a),y,c>>2,b);else{if(b<=288)for(var d=Y[b],e=0;e<b;++e)d[e]=y[c+4*e>>2];else d=y.subarray(c>>2,c+b*4>>2);O.uniform1fv(X(a),d)}},tc:(a,b)=>{O.uniform1i(X(a),b)},_b:(a,b,c)=>{if(W.version>=2)b&&O.uniform1iv(X(a),v,c>>2,b);else{if(b<=288)for(var d=dc[b],e=0;e<b;++e)d[e]=v[c+4*e>>2];else d=v.subarray(c>>2,c+b*4>>2);O.uniform1iv(X(a),d)}},bc:(a,b,c)=>{if(W.version>=2)b&&O.uniform2fv(X(a),y,c>>2,b*2);else{if(b<=144){b*=2;for(var d=Y[b],e=0;e<b;e+=
2)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2]}else d=y.subarray(c>>2,c+b*8>>2);O.uniform2fv(X(a),d)}},Zb:(a,b,c)=>{if(W.version>=2)b&&O.uniform2iv(X(a),v,c>>2,b*2);else{if(b<=144){b*=2;for(var d=dc[b],e=0;e<b;e+=2)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2]}else d=v.subarray(c>>2,c+b*8>>2);O.uniform2iv(X(a),d)}},ac:(a,b,c)=>{if(W.version>=2)b&&O.uniform3fv(X(a),y,c>>2,b*3);else{if(b<=96){b*=3;for(var d=Y[b],e=0;e<b;e+=3)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2],d[e+2]=y[c+(4*e+8)>>2]}else d=y.subarray(c>>2,
c+b*12>>2);O.uniform3fv(X(a),d)}},Yb:(a,b,c)=>{if(W.version>=2)b&&O.uniform3iv(X(a),v,c>>2,b*3);else{if(b<=96){b*=3;for(var d=dc[b],e=0;e<b;e+=3)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2]}else d=v.subarray(c>>2,c+b*12>>2);O.uniform3iv(X(a),d)}},$b:(a,b,c)=>{if(W.version>=2)b&&O.uniform4fv(X(a),y,c>>2,b*4);else{if(b<=72){var d=Y[4*b],e=y;c>>=2;b*=4;for(var f=0;f<b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=y.subarray(c>>2,c+b*16>>2);O.uniform4fv(X(a),
d)}},Xb:(a,b,c)=>{if(W.version>=2)b&&O.uniform4iv(X(a),v,c>>2,b*4);else{if(b<=72){b*=4;for(var d=dc[b],e=0;e<b;e+=4)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2],d[e+3]=v[c+(4*e+12)>>2]}else d=v.subarray(c>>2,c+b*16>>2);O.uniform4iv(X(a),d)}},Wb:(a,b,c,d)=>{if(W.version>=2)b&&O.uniformMatrix4fv(X(a),!!c,y,d>>2,b*16);else{if(b<=18){var e=Y[16*b],f=y;d>>=2;b*=16;for(var g=0;g<b;g+=16){var l=d+g;e[g]=f[l];e[g+1]=f[l+1];e[g+2]=f[l+2];e[g+3]=f[l+3];e[g+4]=f[l+4];e[g+5]=f[l+5];e[g+6]=f[l+
6];e[g+7]=f[l+7];e[g+8]=f[l+8];e[g+9]=f[l+9];e[g+10]=f[l+10];e[g+11]=f[l+11];e[g+12]=f[l+12];e[g+13]=f[l+13];e[g+14]=f[l+14];e[g+15]=f[l+15]}}else e=y.subarray(d>>2,d+b*64>>2);O.uniformMatrix4fv(X(a),!!c,e)}},p:a=>{a=Q[a];O.useProgram(a);O.Zd=a},ec:(a,b)=>{O.vertexAttribDivisor(a,b)},fc:(a,b,c,d,e)=>{O.vertexAttribIPointer(a,b,c,d,e)},gc:(a,b,c,d,e,f)=>{O.vertexAttribPointer(a,b,c,!!d,e,f)},nc:(a,b,c,d)=>O.viewport(a,b,c,d),ub:Pa,ib:(a,b)=>fc(B.subarray(a,a+b)),zb:function(){h.Pd=a=>{qc()!=0&&(a.preventDefault(),
a.returnValue=" ")};window.addEventListener("beforeunload",h.Pd)},yb:function(){h.Ud=a=>{var b=a.clipboardData.getData("text");lc(()=>{var c=ic(b);pc(c)})};window.addEventListener("paste",h.Ud)},xb:function(){h.Je=[];h.Qd=b=>{b.stopPropagation();b.preventDefault()};h.Rd=b=>{b.stopPropagation();b.preventDefault()};h.Sd=b=>{b.stopPropagation();b.preventDefault()};h.Td=b=>{b.stopPropagation();b.preventDefault();var c=b.dataTransfer.files;h.Ke=c;rc(c.length);for(let e=0;e<c.length;e++)lc(()=>{var f=ic(c[e].name);
sc(e,f)});var d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);tc(b.clientX,b.clientY,d)};var a=h.gd;a.addEventListener("dragenter",h.Qd,!1);a.addEventListener("dragleave",h.Rd,!1);a.addEventListener("dragover",h.Sd,!1);a.addEventListener("drop",h.Td,!1)},rb:function(){var a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},sb:function(a){h.sd&&(URL.revokeObjectURL(h.sd[a].fe),h.sd[a]=null)},Za:function(a,b){b!==0&&(document.title=b?G(B,b):"");
a=a?G(B,a):"";h.canvas!==void 0&&(typeof h.canvas==="object"?lb[a]=h.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));h.gd=I(a);h.gd||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);h.gd.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},nb:function(){window.removeEventListener("beforeunload",h.Pd)},mb:function(){window.removeEventListener("paste",h.Ud)},lb:function(){var a=h.gd;a.removeEventListener("dragenter",
h.Qd);a.removeEventListener("dragleave",h.Rd);a.removeEventListener("dragover",h.Sd);a.removeEventListener("drop",h.Td)},s:function(){h.gd&&h.gd.requestPointerLock&&h.gd.requestPointerLock()},tb:function(a,b,c){if(h.gd){if(b===0)a="none";else if(c!=0)a=h.sd[a].he;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";
break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}h.gd.style.cursor=a}},qb:function(a,b,c){var d=document.createElement("canvas");d.width=a;d.height=b;var e=d.getContext("2d"),f=e.createImageData(a,b);f.data.set(B.subarray(c,c+a*b*4));e.putImageData(f,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},ca:function(a,b){b=b?G(B,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);
break;case 2:console.warn(b);break;default:console.info(b)}}};function yc(a=[]){var b=oc;a.unshift(ba);var c=a.length,d=hc((c+1)*4),e=d,f;for(f of a)A[e>>2]=ic(f),e+=4;A[e>>2]=0;try{var g=b(c,d);ha=g;Pa(g)}catch(l){Oa(l)}}
function Cc(a=aa){function b(){h.calledRun=!0;if(!q){Dc.Hc();h.onRuntimeInitialized?.();h.noInitialRun||yc(a);if(h.postRun)for(typeof h.postRun=="function"&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();qa.push(c)}pa(qa)}}if(C>0)ta=Cc;else{if(h.preRun)for(typeof h.preRun=="function"&&(h.preRun=[h.preRun]);h.preRun.length;)sa();pa(ra);C>0?ta=Cc:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b()}}var Dc;
(async function(){function a(c){c=Dc=c.exports;oc=h._main=c.Ic;h._oayao_set_days_counter_start_ms=c.Jc;h._trigger_meteor_shower=c.Kc;pc=h.__sapp_emsc_onpaste=c.Lc;qc=h.__sapp_html5_get_ask_leave_site=c.Mc;rc=h.__sapp_emsc_begin_drop=c.Nc;sc=h.__sapp_emsc_drop=c.Oc;tc=h.__sapp_emsc_end_drop=c.Pc;h.__sapp_emsc_invoke_fetch_cb=c.Qc;h.__sapp_emsc_set_fullscreen_flag=c.Rc;uc=c.Sc;ya=c.Tc;Ha=c.Uc;vc=c.Vc;N=c.Wc;kc=c.Xc;hc=c.Yc;jc=c.Zc;wc=c.Gc;ob=c._c;c=wc.buffer;w=new Int8Array(c);u=new Int16Array(c);B=
new Uint8Array(c);oa=new Uint16Array(c);v=new Int32Array(c);A=new Uint32Array(c);y=new Float32Array(c);z=new Float64Array(c);na=new BigInt64Array(c);new BigUint64Array(c);C--;h.monitorRunDependencies?.(C);C==0&&ta&&(c=ta,ta=null,c());return Dc}C++;h.monitorRunDependencies?.(C);var b={a:xc};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{c(a(d,e))})});ia??=h.locateFile?h.locateFile("oayao.wasm",da):da+"oayao.wasm";return function(c){return a(c.instance)}(await la(b))})();Cc();
