var h;h||=typeof Module != 'undefined' ? Module : {};var aa=[],ba="./this.program",ca=globalThis.document?.currentScript?.src,da="",ea;try{da=(new URL(".",ca)).href}catch{}ea=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var fa=console.log.bind(console),k=console.error.bind(console),l,p=!1,ha;
function r(a){h.onAbort?.(a);a=`Aborted(${a})`;k(a);p=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ia;async function ja(a){if(!l)try{var b=await ea(a);return new Uint8Array(b)}catch{}if(a==ia&&l)a=new Uint8Array(l);else throw"both async and sync fetching of the wasm failed";return a}async function ka(a,b){try{var c=await ja(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),r(d)}}
async function la(a){var b=ia;if(!l)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return ka(b,a)}class ma{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var u,v,w,x,y,A,na,B,C,oa=a=>{for(;a.length>0;)a.shift()(h)},pa=[],qa=[],ra=()=>{var a=h.preRun.shift();qa.push(a)},F=0,G=null,sa=!0;
function ta(){r("missing function: $SOCKFS")}function ua(){r("missing function: $FS")}
var H=a=>{a=ta.ie(a);if(!a)throw new ua.Ld(8);return a},va=a=>{a=a.split(".");for(var b=0;b<4;b++){var c=Number(a[b]);if(isNaN(c))return null;a[b]=c}return(a[0]|a[1]<<8|a[2]<<16|a[3]<<24)>>>0},xa=a=>{var b,c,d=[];if(!/^((?=.*::)(?!.*::.+::)(::)?([\dA-F]{1,4}:(:|\b)|){5}|([\dA-F]{1,4}:){6})((([\dA-F]{1,4}((?!\3)::|:\b|$))|(?!\2\3)){2}|(((2[0-4]|1\d|[1-9])?\d|25[0-5])\.?\b){4})$/i.test(a))return null;if(a==="::")return[0,0,0,0,0,0,0,0];a=a.startsWith("::")?a.replace("::","Z:"):a.replace("::",":Z:");
a.indexOf(".")>0?(a=a.replace(RegExp("[.]","g"),":"),a=a.split(":"),a[a.length-4]=Number(a[a.length-4])+Number(a[a.length-3])*256,a[a.length-3]=Number(a[a.length-2])+Number(a[a.length-1])*256,a=a.slice(0,a.length-2)):a=a.split(":");for(b=c=0;b<a.length;b++)if(typeof a[b]=="string")if(a[b]==="Z"){for(c=0;c<8-a.length+1;c++)d[b+c]=0;--c}else d[b+c]=wa(parseInt(a[b],16));else d[b+c]=a[b];return[d[1]<<16|d[0],d[3]<<16|d[2],d[5]<<16|d[4],d[7]<<16|d[6]]},za=(a,b,c,d,e)=>{switch(b){case 2:c=va(c);C.fill(0,
a,a+16);e&&(v[e>>2]=16);u[a>>1]=b;v[a+4>>2]=c;u[a+2>>1]=wa(d);break;case 10:c=xa(c),C.fill(0,a,a+28),e&&(v[e>>2]=28),v[a>>2]=b,v[a+8>>2]=c[0],v[a+12>>2]=c[1],v[a+16>>2]=c[2],v[a+20>>2]=c[3],u[a+2>>1]=wa(d)}},Aa=1,Ba={},Ca={};function Da(a){var b=va(a);if(b!==null)return a;b=xa(a);if(b!==null)return a;Ba[a]?b=Ba[a]:(b=Aa++,b="172.29."+(b&255)+"."+(b&65280),Ca[b]=a,Ba[a]=b);return b}
var Ea=a=>(a&255)+"."+(a>>8&255)+"."+(a>>16&255)+"."+(a>>24&255),Ga=a=>{var b="",c,d=0,e=0,f=0,g=0;a=[a[0]&65535,a[0]>>16,a[1]&65535,a[1]>>16,a[2]&65535,a[2]>>16,a[3]&65535,a[3]>>16];var m=!0;for(c=0;c<5;c++)if(a[c]!==0){m=!1;break}if(m){c=Ea(a[6]|a[7]<<16);if(a[5]===-1)return"::ffff:"+c;if(a[5]===0)return c==="0.0.0.0"&&(c=""),c==="0.0.0.1"&&(c="1"),"::"+c}for(c=0;c<8;c++)a[c]===0&&(c-e>1&&(g=0),e=c,g++),g>d&&(d=g,f=c-d+1);for(c=0;c<8;c++)d>1&&a[c]===0&&c>=f&&c<f+d?c===f&&(b+=":",f===0&&(b+=":")):
(b+=Number(Fa(a[c]&65535)).toString(16),b+=c<7?":":"");return b},Ha=(a,b)=>{var c=u[a>>1],d=Fa(na[a+2>>1]);switch(c){case 2:if(b!==16)return{Zc:28};a=v[a+4>>2];a=Ea(a);break;case 10:if(b!==28)return{Zc:28};a=[v[a+8>>2],v[a+12>>2],v[a+16>>2],v[a+20>>2]];a=Ga(a);break;default:return{Zc:5}}return{family:c,Xc:a,port:d}},Ia=(a,b)=>{a=Ha(a,b);if(a.Zc)throw new ua.Ld(a.Zc);b=a.Xc;a.Xc=(Ca[b]?Ca[b]:null)||a.Xc;return a},Ja=globalThis.TextDecoder&&new TextDecoder,I=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=
c);)++d;if(d-b>16&&a.buffer&&Ja)return Ja.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var f=a[b++]&63;if((e&224)==192)c+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=(e&240)==224?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;e<65536?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},Ka=0,J={},La=a=>{if(!(a instanceof ma||a=="unwind"))throw a;},Ma=a=>{ha=a;sa||Ka>0||(h.onExit?.(a),p=!0);throw new ma(a);
},Na=()=>{if(!(sa||Ka>0))try{var a=ha;ha=a;Ma(a)}catch(b){La(b)}},Oa=a=>{if(!p)try{a()}catch(b){La(b)}finally{Na()}},Xa=(a,b)=>{Pa=a;Qa=b;if(Ra)if(Sa||=!0,a==0)K=function(){setTimeout(Ta,Math.max(0,Ua+b-performance.now())|0)};else if(a==1)K=function(){Va(Ta)};else{if(!Wa)if(globalThis.scheduler)Wa=scheduler.postTask.bind(scheduler);else{var c=[];addEventListener("message",d=>{d.data==="setimmediate"&&(d.stopPropagation(),c.shift()())},!0);Wa=d=>{c.push(d);postMessage("setimmediate","*")}}K=function(){Wa(Ta)}}},
fb=(a,b,c,d,e)=>{function f(){return g<Ya?(Na(),!1):!0}Ra=a;Za=d;var g=Ya;Sa=!1;Ta=function(){if(!p)if($a.length>0){var m=$a.shift();m.ge(m.Sd);if(ab){var n=ab,q=n%1==0?n-1:Math.floor(n);ab=m.Vd?q:(8*n+(q+.5))/9}h.setStatus&&(m=h.statusMessage||"Please wait...",n=ab??0,q=bb.ce??0,n?n<q?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(m):h.setStatus(""));f()&&setTimeout(Ta,0)}else if(f())if(cb=cb+1|0,Pa==1&&Qa>1&&cb%Qa!=0)K();else{Pa==0&&(Ua=performance.now());a:if(!p){for(m of db)if(m()===
!1)break a;Oa(a);for(n of eb)n()}f()&&K()}};e||(b>0?Xa(0,1E3/b):Xa(1,1),K());if(c)throw"unwind";},Sa=!1,K=null,Ya=0,Ra=null,Za=0,Pa=0,Qa=0,cb=0,$a=[],db=[],eb=[];function gb(){K=null;Ya++}var hb=0;function Va(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(hb===0)hb=b+1E3/60;else for(;b+2>=hb;)hb+=1E3/60;setTimeout(a,Math.max(hb-b,0))}}
var bb={},Ua,Ta,Wa,ab,ib=[0,document,window],L=a=>{a=a>2?a?I(C,a):"":a;return ib[a]||document.querySelector(a)},jb=a=>ib.indexOf(a)<0?a.getBoundingClientRect():{left:0,top:0},kb=[],M=a=>{var b=kb[a];b||(kb[a]=b=lb.get(a));return b};function mb(a){var b=N.Pc[a];b.target.removeEventListener(b.Oc,b.yd,b.Sc);N.Pc.splice(a,1)}function nb(){if(navigator.userActivation?navigator.userActivation.isActive:N.jd&&N.Md.fd){var a=N.Wc;N.Wc=[];for(var b of a)b.md(...b.td)}}
function O(a){if(!a.target)return-4;if(a.Qc)a.yd=function(c){++N.jd;N.Md=a;nb();a.Uc(c);nb();--N.jd},a.target.addEventListener(a.Oc,a.yd,a.Sc),N.Pc.push(a);else for(var b=0;b<N.Pc.length;++b)N.Pc[b].target==a.target&&N.Pc[b].Oc==a.Oc&&mb(b--);return 0}function ob(a){return a==window?"#window":a==screen?"#screen":a?.nodeName??""}
var N={Td:0,he:0,kd:0,cd:0,qd:0,od:0,gd:0,$d:0,ne:0,Zd:0,hd:0,ld:0,Be:0,nd:0,qe(){for(;N.Pc.length;)mb(N.Pc.length-1);N.Wc=[]},jd:0,Wc:[],Yd(a,b,c){function d(f,g){if(f.length!=g.length)return!1;for(var m in f)if(f[m]!=g[m])return!1;return!0}for(var e of N.Wc)if(e.md==a&&d(e.td,c))return;N.Wc.push({md:a,Cd:b,td:c});N.Wc.sort((f,g)=>f.Cd-g.Cd)},se(a){N.Wc=N.Wc.filter(b=>b.md!=a)},Pc:[],re:(a,b)=>{for(var c=0;c<N.Pc.length;++c)N.Pc[c].target!=a||b&&b!=N.Pc[c].Oc||mb(c--)},te(a){var b=!1;for(let c=0;c<
N.Pc.length;++c){let d=N.Pc[c];d.target===a.target&&d.Rc===a.Rc&&d.Qc===a.Qc&&d.Tc===a.Tc&&(mb(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},P=(a,b,c)=>{var d=C;if(!(c>0))return 0;var e=b;c=b+c-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(g<=127){if(b>=c)break;d[b++]=g}else if(g<=2047){if(b+1>=c)break;d[b++]=192|g>>6;d[b++]=128|g&63}else if(g<=65535){if(b+2>=c)break;d[b++]=224|g>>12;d[b++]=128|g>>6&63;d[b++]=128|g&63}else{if(b+
3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63;d[b++]=128|g>>6&63;d[b++]=128|g&63;f++}}d[b]=0;return b-e},pb=(a,b,c,d,e,f)=>{N.gd||(N.gd=Q(256));a={target:L(a),Oc:f,Rc:e,Tc:b,Qc:d,Uc:g=>{var m=g.target.id??"",n=N.gd;P(ob(g.target),n+0,128);P(m,n+128,128);M(d)(e,n,b)&&g.preventDefault()},Sc:c};return O(a)},qb=(a,b,c,d,e)=>{N.hd||(N.hd=Q(276));return O({target:a,Oc:e,Rc:19,Tc:b,Qc:d,Uc:f=>{var g=N.hd,m=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||
document.msFullscreenElement,n=!!m;x[g]=n;x[g+1]=N.fullscreenEnabled();var q=n?m:N.Qd,t=q?.id??"";P(ob(q),g+2,128);P(t,g+130,128);v[g+260>>2]=q?.clientWidth??0;v[g+264>>2]=q?.clientHeight??0;v[g+268>>2]=screen.width;v[g+272>>2]=screen.height;n&&(N.Qd=m);M(d)(19,g,b)&&f.preventDefault()},Sc:c})},rb=(a,b,c,d,e,f)=>{N.kd||(N.kd=Q(160));a={target:L(a),Oc:f,Rc:e,Tc:b,Qc:d,Uc:g=>{var m=N.kd;A[m>>3]=g.timeStamp;var n=m>>2;v[n+2]=g.location;x[m+12]=g.ctrlKey;x[m+13]=g.shiftKey;x[m+14]=g.altKey;x[m+15]=g.metaKey;
x[m+16]=g.repeat;v[n+5]=g.charCode;v[n+6]=g.keyCode;v[n+7]=g.which;P(g.key??"",m+32,32);P(g.code??"",m+64,32);P(g.char??"",m+96,32);P(g.locale??"",m+128,32);M(d)(e,m,b)&&g.preventDefault()},Sc:c};return O(a)},sb=(a,b,c)=>{A[a>>3]=b.timeStamp;var d=a>>2;v[d+2]=b.screenX;v[d+3]=b.screenY;v[d+4]=b.clientX;v[d+5]=b.clientY;x[a+24]=b.ctrlKey;x[a+25]=b.shiftKey;x[a+26]=b.altKey;x[a+27]=b.metaKey;u[d*2+14]=b.button;u[d*2+15]=b.buttons;v[d+8]=b.movementX;v[d+9]=b.movementY;a=jb(c);v[d+10]=b.clientX-(a.left|
0);v[d+11]=b.clientY-(a.top|0)},tb=(a,b,c,d,e,f)=>{N.cd||(N.cd=Q(64));a=L(a);return O({target:a,fd:f!="mousemove"&&f!="mouseenter"&&f!="mouseleave",Oc:f,Rc:e,Tc:b,Qc:d,Uc:g=>{sb(N.cd,g,a);M(d)(e,N.cd,b)&&g.preventDefault()},Sc:c})},ub=(a,b,c,d)=>{N.ld||(N.ld=Q(257));return O({target:a,Oc:"pointerlockchange",Rc:20,Tc:b,Qc:d,Uc:e=>{var f=N.ld,g=document.pointerLockElement;x[f]=!!g;var m=g?.id??"";P(ob(g),f+1,128);P(m,f+129,128);M(d)(20,f,b)&&e.preventDefault()},Sc:c})},vb=(a,b,c,d)=>O({target:a,Oc:"pointerlockerror",
Rc:38,Tc:b,Qc:d,Uc:e=>{M(d)(38,0,b)&&e.preventDefault()},Sc:c}),wb=(a,b,c,d)=>{N.od||(N.od=Q(36));a=L(a);return O({target:a,Oc:"resize",Rc:10,Tc:b,Qc:d,Uc:e=>{if(e.target==a){var f=document.body;if(f){var g=N.od;v[g>>2]=0;v[g+4>>2]=f.clientWidth;v[g+8>>2]=f.clientHeight;v[g+12>>2]=innerWidth;v[g+16>>2]=innerHeight;v[g+20>>2]=outerWidth;v[g+24>>2]=outerHeight;v[g+28>>2]=pageXOffset|0;v[g+32>>2]=pageYOffset|0;M(d)(10,g,b)&&e.preventDefault()}}},Sc:c})},xb=(a,b,c,d,e,f)=>{N.nd||(N.nd=Q(1552));a=L(a);
return O({target:a,fd:f=="touchstart"||f=="touchend",Oc:f,Rc:e,Tc:b,Qc:d,Uc:g=>{var m={},n=g.touches;for(var q of n)q.zd=q.Bd=0,m[q.identifier]=q;for(var t of g.changedTouches)t.zd=1,m[t.identifier]=t;for(var z of g.targetTouches)m[z.identifier].Bd=1;n=N.nd;A[n>>3]=g.timeStamp;x[n+12]=g.ctrlKey;x[n+13]=g.shiftKey;x[n+14]=g.altKey;x[n+15]=g.metaKey;q=n+16;t=jb(a);z=0;for(let D of Object.values(m))if(m=q>>2,v[m]=D.identifier,v[m+1]=D.screenX,v[m+2]=D.screenY,v[m+3]=D.clientX,v[m+4]=D.clientY,v[m+5]=
D.pageX,v[m+6]=D.pageY,x[q+28]=D.zd,x[q+29]=D.Bd,v[m+8]=D.clientX-(t.left|0),v[m+9]=D.clientY-(t.top|0),q+=48,++z>31)break;v[n+8>>2]=z;M(d)(e,n,b)&&g.preventDefault()},Sc:c})},R,yb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},zb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&
(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Ab=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Bb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return a.getSupportedExtensions()?.filter(c=>b.includes(c))??[]},Cb=1,S=[],T=[],Db=[],Eb=[],Fb=[],U=[],Gb=[],Hb=[],Ib=[],Jb={},Kb=a=>{for(var b=Cb++,c=a.length;c<b;c++)a[c]=null;return b},Lb=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=R[c](),g=f&&Kb(d);f?(f.name=g,d[g]=f):V||=1282;v[b+e*4>>2]=g}},Nb=(a,b)=>{a.sd||(a.sd=a.getContext,a.getContext=function(d,e){e=a.sd(d,e);return d=="webgl"==e instanceof WebGLRenderingContext?e:null});var c=b.Ad>1?a.getContext("webgl2",b):a.getContext("webgl",b);return c?
Mb(c,b):0},Mb=(a,b)=>{var c=Kb(Hb),d={handle:c,attributes:b,version:b.Ad,rd:a};a.canvas&&(a.canvas.Rd=d);Hb[c]=d;if(typeof b.xd=="undefined"||b.xd)if((a=d)||(a=W),!a.Pd){a.Pd=!0;b=a.rd;b.me=b.getExtension("WEBGL_multi_draw");b.ee=b.getExtension("EXT_polygon_offset_clamp");b.de=b.getExtension("EXT_clip_control");b.Ce=b.getExtension("WEBGL_polygon_mode");yb(b);zb(b);Ab(b);b.ae=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.ke=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
a.version>=2&&(b.wd=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(a.version<2||!b.wd)b.wd=b.getExtension("EXT_disjoint_timer_query");for(var e of Bb(b))e.includes("lose_context")||e.includes("debug")||b.getExtension(e)}return c},V,W,Ob=(a,b,c,d,e,f)=>{a={target:L(a),Oc:f,Rc:e,Tc:b,Qc:d,Uc:g=>{M(d)(e,0,b)&&g.preventDefault()},Sc:c};O(a)},Pb=(a,b,c,d)=>{N.qd||(N.qd=Q(96));return O({target:a,fd:!0,Oc:"wheel",Rc:9,Tc:b,Qc:d,Uc:e=>{var f=N.qd;sb(f,e,a);A[f+64>>3]=e.deltaX;A[f+72>>3]=e.deltaY;A[f+
80>>3]=e.deltaZ;v[f+88>>2]=e.deltaMode;M(d)(9,f,b)&&e.preventDefault()},Sc:c})},Qb=["default","low-power","high-performance"],Rb={},Tb=()=>{if(!Sb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ba},b;for(b in Rb)Rb[b]===void 0?delete a[b]:a[b]=Rb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Sb=c}return Sb},Sb,Ub=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);d<=127?b++:d<=2047?b+=
2:d>=55296&&d<=57343?(b+=4,++c):b+=3}return b},Vb=[null,[],[]],Wb=[],Xb=()=>{var a=Bb(R);return a=a.concat(a.map(b=>"GL_"+b))},Yb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=R.getParameter(34467);c=d?d.length:0;break;case 33309:if(W.version<2){V||=1282;return}c=Xb().length;break;case 33307:case 33308:if(W.version<2){V||=1280;return}c=a==33307?3:0}if(c===void 0)switch(d=R.getParameter(a),typeof d){case "number":c=d;break;
case "boolean":c=d?1:0;break;case "string":V||=1280;return;case "object":if(d===null)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:V||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)v[b+a*4>>2]=d[a];return}try{c=d.name|
0}catch(e){V||=1280;k(`GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:V||=1280;k(`GL_INVALID_ENUM in glGet0v: Native code calling glGet0v(${a}) and it returns ${d} of type ${typeof d}!`);return}v[b>>2]=c}else V||=1281},Zb=a=>{var b=Ub(a)+1,c=Q(b);c&&P(a,c,b);return c},$b=a=>a.slice(-1)=="]"&&a.lastIndexOf("["),X=a=>{var b=R.Nd;if(b){var c=b.Yc[a];typeof c=="number"&&(b.Yc[a]=c=R.getUniformLocation(b,b.Jd[a]+(c>0?`[${c}]`:"")));
return c}V||=1282},Y=[],ac=[],bc=()=>a=>(crypto.getRandomValues(a),0),cc=a=>(cc=bc())(a),ec=a=>{var b=Ub(a)+1,c=dc(b);P(a,c,b);return c},ic=a=>{var b=fc();a();hc(b)};h.requestAnimationFrame=Va;h.pauseMainLoop=gb;h.resumeMainLoop=function(){Ya++;var a=Pa,b=Qa,c=Ra;Ra=null;fb(c,0,!1,Za,!0);Xa(a,b);K()};h.preMainLoop&&db.push(h.preMainLoop);h.postMainLoop&&eb.push(h.postMainLoop);for(let a=0;a<32;++a)Wb.push(Array(a));for(var jc=new Float32Array(288),Z=0;Z<=288;++Z)Y[Z]=jc.subarray(0,Z);var kc=new Int32Array(288);
for(Z=0;Z<=288;++Z)ac[Z]=kc.subarray(0,Z);h.noExitRuntime&&(sa=h.noExitRuntime);h.print&&(fa=h.print);h.printErr&&(k=h.printErr);h.wasmBinary&&(l=h.wasmBinary);h.arguments&&(aa=h.arguments);h.thisProgram&&(ba=h.thisProgram);if(h.preInit)for(typeof h.preInit=="function"&&(h.preInit=[h.preInit]);h.preInit.length>0;)h.preInit.shift()();
var lc,mc,nc,oc,pc,qc,rc,wa,Fa,sc,Q,hc,dc,fc,tc,lb,uc={y:(a,b,c)=>{a=H(a);a=a.dd.accept(a);b&&za(b,a.family,Da(a.Xd),a.be,c);return a.stream.fe},Aa:(a,b,c)=>{H(a);Ia(b,c);return 0},G:()=>{},Va:()=>{},Ba:(a,b,c)=>{a=H(a);b=Ia(b,c);a.dd.connect(a,b.Xc,b.port);return 0},Ha:()=>{},$a:()=>{},Wa:()=>{},D:()=>{},Sa:()=>{},f:function(){return 0},Oa:()=>{},Ta:function(){},_a:()=>{},eb:(a,b,c)=>{a=H(a);za(b,a.family,Da(a.ve||"0.0.0.0"),a.ze,c);return 0},I:function(){return 0},za:(a,b)=>{a=H(a);a.dd.je(a,b);
return 0},Ma:()=>{},Ga:()=>{},La:()=>{},B:function(){},Fa:()=>{},A:()=>{},Ea:(a,b)=>{var c=H(a);a=B[b+8>>2];for(var d=v[b+12>>2],e=0,f=0;f<d;f++)e+=v[a+(8*f+4)>>2];e=c.dd.pe(c,e);if(!e)return 0;(f=B[b>>2])&&za(f,c.family,Da(e.Xc),e.port);b=0;c=e.buffer.byteLength;for(f=0;c>0&&f<d;f++){var g=v[a+(8*f+4)>>2];g&&(g=Math.min(g,c),C.set(e.buffer.subarray(b,b+g),B[a+8*f>>2]+b),b+=g,c-=g)}return b},Ja:()=>{},Ca:(a,b)=>{a=H(a);var c=B[b+8>>2],d=v[b+12>>2],e=B[b>>2];b=v[b+4>>2];if(e){var f=Ia(e,b);var g=f.port;
f=f.Xc}for(e=b=0;e<d;e++)b+=v[c+(8*e+4)>>2];var m=new Uint8Array(b),n=0;for(e=0;e<d;e++)for(var q=B[c+8*e>>2],t=v[c+(8*e+4)>>2],z=0;z<t;z++)m[n++]=x[q+z];return a.dd.we(a,m,0,b,f,g)},J:()=>{},Na:()=>{},Ka:()=>{},Ia:()=>{},Xa:()=>{},wb:()=>r(""),vb:()=>{sa=!1;Ka=0},Ya:function(){return-52},Za:function(){},xb:(a,b)=>{J[a]&&(clearTimeout(J[a].id),delete J[a]);if(!b)return 0;var c=setTimeout(()=>{delete J[a];Oa(()=>sc(a,performance.now()))},b);J[a]={id:c,Ae:b};return 0},bb:(a,b)=>{if(!(a>=0&&a<=3))return 28;
var c;a===0?c=1E6:c=1E3;w[b>>3]=BigInt(c);return 0},cb:function(a,b,c){if(!(a>=0&&a<=3))return 28;w[c>>3]=BigInt(Math.round((a===0?Date.now():performance.now())*1E3*1E3));return 0},jb:()=>{gb();Ra=null},ua:()=>devicePixelRatio,C:(a,b,c)=>{a=L(a);if(!a)return-4;a=jb(a);A[b>>3]=a.width;A[c>>3]=a.height;return 0},p:()=>performance.now(),kb:()=>performance.now(),qb:(a,b)=>{function c(d){M(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},rc:()=>{r("OOM")},N:(a,b,c,d)=>pb(a,b,c,d,12,"blur"),
ra:(a,b,c)=>{a=L(a);if(!a)return-4;a.width=b;a.height=c;return 0},O:(a,b,c,d)=>pb(a,b,c,d,13,"focus"),M:(a,b,c,d)=>{if(!N.fullscreenEnabled())return-1;a=L(a);if(!a)return-4;qb(a,b,c,d,"webkitfullscreenchange");return qb(a,b,c,d,"fullscreenchange")},X:(a,b,c,d)=>rb(a,b,c,d,2,"keydown"),V:(a,b,c,d)=>rb(a,b,c,d,1,"keypress"),W:(a,b,c,d)=>rb(a,b,c,d,3,"keyup"),rb:(a,b,c)=>{a=M(a);fb(a,b,c)},ea:(a,b,c,d)=>tb(a,b,c,d,5,"mousedown"),_:(a,b,c,d)=>tb(a,b,c,d,33,"mouseenter"),Z:(a,b,c,d)=>tb(a,b,c,d,34,"mouseleave"),
ba:(a,b,c,d)=>tb(a,b,c,d,8,"mousemove"),da:(a,b,c,d)=>tb(a,b,c,d,6,"mouseup"),Q:(a,b,c,d)=>document.body?.requestPointerLock?(a=L(a))?ub(a,b,c,d):-4:-1,P:(a,b,c,d)=>document.body?.requestPointerLock?(a=L(a))?vb(a,b,c,d):-4:-1,z:(a,b,c,d)=>wb(a,b,c,d),R:(a,b,c,d)=>xb(a,b,c,d,25,"touchcancel"),S:(a,b,c,d)=>xb(a,b,c,d,23,"touchend"),T:(a,b,c,d)=>xb(a,b,c,d,24,"touchmove"),U:(a,b,c,d)=>xb(a,b,c,d,22,"touchstart"),L:(a,b,c,d)=>{Ob(a,b,c,d,31,"webglcontextlost");return 0},K:(a,b,c,d)=>{Ob(a,b,c,d,32,"webglcontextrestored");
return 0},Y:(a,b,c,d)=>(a=L(a))?typeof a.onwheel!="undefined"?Pb(a,b,c,d):-1:-4,hc:(a,b)=>{var c=b>>2;b={alpha:!!x[b+0],depth:!!x[b+1],stencil:!!x[b+2],antialias:!!x[b+3],premultipliedAlpha:!!x[b+4],preserveDrawingBuffer:!!x[b+5],powerPreference:Qb[v[c+2]],failIfMajorPerformanceCaveat:!!x[b+12],Ad:v[c+4],le:v[c+5],xd:x[b+24],Od:x[b+25],oe:v[c+7],ue:x[b+32]};a=L(a);return!a||b.Od?0:Nb(a,b)},dc:a=>{W=Hb[a];h.ctx=R=W?.rd;return!a||R?0:-5},ab:(a,b)=>{var c=0,d=0,e;for(e of Tb()){var f=b+c;B[a+d>>2]=f;
c+=P(e,f,Infinity)+1;d+=4}return 0},sc:(a,b)=>{var c=Tb();B[a>>2]=c.length;a=0;for(var d of c)a+=Ub(d)+1;B[b>>2]=a;return 0},o:()=>52,H:(a,b)=>{var c=0;if(a==0)c=2;else if(a==1||a==2)c=64;x[b]=2;u[b+2>>1]=1;w[b+8>>3]=BigInt(c);w[b+16>>3]=BigInt(0);return 0},E:function(){return 52},F:function(){return 52},Da:()=>52,Qa:function(){return 70},Ra:()=>52,Pa:(a,b,c,d)=>{for(var e=0,f=0;f<c;f++){var g=B[b>>2],m=B[b+4>>2];b+=8;for(var n=0;n<m;n++){var q=a,t=C[g+n],z=Vb[q];t===0||t===10?((q===1?fa:k)(I(z)),
z.length=0):z.push(t)}e+=m}B[d>>2]=e;return 0},fb:(a,b,c,d)=>{function e(z,D,wc,xc,E,yc){var ya=z===10?28:16;E=z===10?Ga(E):Ea(E);ya=Q(ya);za(ya,z,E,yc);E=Q(32);v[E+4>>2]=z;v[E+8>>2]=D;v[E+12>>2]=wc;B[E+24>>2]=xc;B[E+20>>2]=ya;v[E+16>>2]=z===10?28:16;v[E+28>>2]=0;return E}var f=0,g=0,m=0,n=0,q=0,t=0;c&&(m=v[c>>2],n=v[c+4>>2],q=v[c+8>>2],t=v[c+12>>2]);q&&!t&&(t=q===2?17:6);!q&&t&&(q=t===17?2:1);t===0&&(t=6);q===0&&(q=1);if(!a&&!b)return-2;if(m&-1088||c!==0&&v[c>>2]&2&&!a)return-1;if(m&32)return-2;
if(q!==0&&q!==1&&q!==2)return-7;if(n!==0&&n!==2&&n!==10)return-6;if(b&&(b=b?I(C,b):"",g=parseInt(b,10),isNaN(g)))return m&1024?-2:-8;if(!a)return n===0&&(n=2),(m&1)===0&&(n===2?f=rc(2130706433):f=[0,0,0,rc(1)]),a=e(n,q,t,null,f,g),B[d>>2]=a,0;a=a?I(C,a):"";f=va(a);if(f!==null)if(n===0||n===2)n=2;else if(n===10&&m&8)f=[0,0,rc(65535),f],n=10;else return-2;else if(f=xa(a),f!==null)if(n===0||n===10)n=10;else return-2;if(f!=null)return a=e(n,q,t,a,f,g),B[d>>2]=a,0;if(m&4)return-2;a=Da(a);f=va(a);n===0?
n=2:n===10&&(f=[0,0,rc(65535),f]);a=e(n,q,t,null,f,g);B[d>>2]=a;return 0},s:a=>R.activeTexture(a),v:(a,b)=>{R.attachShader(T[a],U[b])},b:(a,b)=>{a==35051?R.ud=b:a==35052&&(R.vd=b);R.bindBuffer(a,S[b])},ca:(a,b,c)=>{R.bindBufferBase(a,b,S[c])},_b:(a,b,c,d,e)=>{R.bindBufferRange(a,b,S[c],d,e)},j:(a,b)=>{R.bindFramebuffer(a,Db[b])},r:(a,b)=>{R.bindSampler(a,Ib[b])},g:(a,b)=>{R.bindTexture(a,Fb[b])},x:a=>{R.bindVertexArray(Gb[a])},ia:(a,b,c,d)=>R.blendColor(a,b,c,d),ja:(a,b)=>R.blendEquationSeparate(a,
b),ka:(a,b,c,d)=>R.blendFuncSeparate(a,b,c,d),Hb:(a,b,c,d,e,f,g,m,n,q)=>R.blitFramebuffer(a,b,c,d,e,f,g,m,n,q),mc:(a,b,c,d)=>{W.version>=2?c&&b?R.bufferData(a,C,d,c,b):R.bufferData(a,b,d):R.bufferData(a,c?C.subarray(c,c+b):b,d)},sa:(a,b,c,d)=>{var e=C;W.version>=2?c&&R.bufferSubData(a,b,e,d,c):R.bufferSubData(a,b,e.subarray(d,d+c))},yb:a=>R.checkFramebufferStatus(a),cc:(a,b,c,d)=>R.clearBufferfi(a,b,c,d),ma:(a,b,c)=>{R.clearBufferfv(a,b,y,c>>2)},bc:(a,b,c)=>{R.clearBufferiv(a,b,v,c>>2)},i:(a,b,c,
d)=>{R.colorMask(!!a,!!b,!!c,!!d)},Ab:a=>{R.compileShader(U[a])},lc:()=>{var a=Kb(T),b=R.createProgram();b.name=a;b.bd=b.$c=b.ad=0;b.pd=1;T[a]=b;return a},Cb:a=>{var b=Kb(U);U[b]=R.createShader(a);return b},ha:a=>R.cullFace(a),Db:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+c*4>>2],e=S[d];e&&(R.deleteBuffer(e),e.name=0,S[d]=null,d==R.ud&&(R.ud=0),d==R.vd&&(R.vd=0))}},ta:(a,b)=>{for(var c=0;c<a;++c){var d=v[b+c*4>>2],e=Db[d];e&&(R.deleteFramebuffer(e),e.name=0,Db[d]=null)}},m:a=>{if(a){var b=T[a];b?(R.deleteProgram(b),
b.name=0,T[a]=null):V||=1281}},pc:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+c*4>>2],e=Eb[d];e&&(R.deleteRenderbuffer(e),e.name=0,Eb[d]=null)}},qc:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+c*4>>2],e=Ib[d];e&&(R.deleteSampler(e),e.name=0,Ib[d]=null)}},k:a=>{if(a){var b=U[a];b?(R.deleteShader(b),U[a]=null):V||=1281}},w:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+c*4>>2],e=Fb[d];e&&(R.deleteTexture(e),e.name=0,Fb[d]=null)}},oc:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+c*4>>2];R.deleteVertexArray(Gb[d]);Gb[d]=null}},
t:a=>R.depthFunc(a),u:a=>{R.depthMask(!!a)},c:a=>R.disable(a),fa:a=>{R.disableVertexAttribArray(a)},Jb:(a,b,c)=>{R.drawArrays(a,b,c)},Kb:(a,b,c,d)=>{R.drawArraysInstanced(a,b,c,d)},gc:(a,b)=>{for(var c=Wb[a],d=0;d<a;d++)c[d]=v[b+d*4>>2];R.drawBuffers(c)},Lb:(a,b,c,d)=>{R.drawElements(a,b,c,d)},Mb:(a,b,c,d,e)=>{R.drawElementsInstanced(a,b,c,d,e)},d:a=>R.enable(a),Wb:a=>{R.enableVertexAttribArray(a)},h:(a,b,c,d)=>{R.framebufferRenderbuffer(a,b,c,Eb[d])},e:(a,b,c,d,e)=>{R.framebufferTexture2D(a,b,c,
Fb[d],e)},na:(a,b,c,d,e)=>{R.framebufferTextureLayer(a,b,Fb[c],d,e)},ga:a=>R.frontFace(a),nc:(a,b)=>{Lb(a,b,"createBuffer",S)},wa:(a,b)=>{Lb(a,b,"createFramebuffer",Db)},xa:(a,b)=>{Lb(a,b,"createVertexArray",Gb)},ic:(a,b)=>R.getAttribLocation(T[a],b?I(C,b):""),a:(a,b)=>Yb(a,b),kc:(a,b,c,d)=>{a=R.getProgramInfoLog(T[a]);a===null&&(a="(unknown error)");b=b>0&&d?P(a,d,b):0;c&&(v[c>>2]=b)},pa:(a,b,c)=>{if(c)if(a>=Cb)V||=1281;else if(a=T[a],b==35716)a=R.getProgramInfoLog(a),a===null&&(a="(unknown error)"),
v[c>>2]=a.length+1;else if(b==35719){if(!a.bd){var d=R.getProgramParameter(a,35718);for(b=0;b<d;++b)a.bd=Math.max(a.bd,R.getActiveUniform(a,b).name.length+1)}v[c>>2]=a.bd}else if(b==35722){if(!a.$c)for(d=R.getProgramParameter(a,35721),b=0;b<d;++b)a.$c=Math.max(a.$c,R.getActiveAttrib(a,b).name.length+1);v[c>>2]=a.$c}else if(b==35381){if(!a.ad)for(d=R.getProgramParameter(a,35382),b=0;b<d;++b)a.ad=Math.max(a.ad,R.getActiveUniformBlockName(a,b).length+1);v[c>>2]=a.ad}else v[c>>2]=R.getProgramParameter(a,
b);else V||=1281},zb:(a,b,c,d)=>{a=R.getShaderInfoLog(U[a]);a===null&&(a="(unknown error)");b=b>0&&d?P(a,d,b):0;c&&(v[c>>2]=b)},aa:(a,b,c)=>{c?b==35716?(a=R.getShaderInfoLog(U[a]),a===null&&(a="(unknown error)"),v[c>>2]=a?a.length+1:0):b==35720?(a=R.getShaderSource(U[a]),v[c>>2]=a?a.length+1:0):v[c>>2]=R.getShaderParameter(U[a],b):V||=1281},ya:(a,b)=>{if(W.version<2)return V||=1282,0;var c=Jb[a];if(c)return b<0||b>=c.length?(V||=1281,0):c[b];switch(a){case 7939:return c=Xb().map(Zb),c=Jb[a]=c,b<0||
b>=c.length?(V||=1281,0):c[b];default:return V||=1280,0}},oa:(a,b)=>{b=b?I(C,b):"";if(a=T[a]){var c=a,d=c.Yc,e=c.Kd,f;if(!d){c.Yc=d={};c.Jd={};var g=R.getProgramParameter(c,35718);for(f=0;f<g;++f){var m=R.getActiveUniform(c,f);var n=m.name;m=m.size;var q=$b(n);q=q>0?n.slice(0,q):n;var t=c.pd;c.pd+=m;e[q]=[m,t];for(n=0;n<m;++n)d[t]=n,c.Jd[t++]=q}}c=a.Yc;d=0;e=b;f=$b(b);f>0&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.Kd[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||R.getUniformLocation(a,b)))return d}else V||=
1281;return-1},Gb:(a,b,c)=>{for(var d=Wb[b],e=0;e<b;e++)d[e]=v[c+e*4>>2];R.invalidateFramebuffer(a,d)},qa:a=>{a=T[a];R.linkProgram(a);a.Yc=0;a.Kd={}},va:(a,b)=>{R.pixelStorei(a,b)},la:(a,b)=>R.polygonOffset(a,b),Ib:a=>R.readBuffer(a),ec:(a,b,c,d)=>R.scissor(a,b,c,d),Bb:(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var g=(g=B[c+f*4>>2])?I(C,g,d?B[d+f*4>>2]:void 0):"";e+=g}R.shaderSource(U[a],e)},Fb:(a,b,c)=>R.stencilFunc(a,b,c),ac:(a,b,c,d)=>R.stencilFuncSeparate(a,b,c,d),l:a=>R.stencilMask(a),Eb:(a,b,c)=>
R.stencilOp(a,b,c),$b:(a,b,c,d)=>R.stencilOpSeparate(a,b,c,d),Vb:(a,b,c)=>{if(W.version>=2)b&&R.uniform1fv(X(a),y,c>>2,b);else{if(b<=288)for(var d=Y[b],e=0;e<b;++e)d[e]=y[c+4*e>>2];else d=y.subarray(c>>2,c+b*4>>2);R.uniform1fv(X(a),d)}},jc:(a,b)=>{R.uniform1i(X(a),b)},Rb:(a,b,c)=>{if(W.version>=2)b&&R.uniform1iv(X(a),v,c>>2,b);else{if(b<=288)for(var d=ac[b],e=0;e<b;++e)d[e]=v[c+4*e>>2];else d=v.subarray(c>>2,c+b*4>>2);R.uniform1iv(X(a),d)}},Ub:(a,b,c)=>{if(W.version>=2)b&&R.uniform2fv(X(a),y,c>>2,
b*2);else{if(b<=144){b*=2;for(var d=Y[b],e=0;e<b;e+=2)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2]}else d=y.subarray(c>>2,c+b*8>>2);R.uniform2fv(X(a),d)}},Qb:(a,b,c)=>{if(W.version>=2)b&&R.uniform2iv(X(a),v,c>>2,b*2);else{if(b<=144){b*=2;for(var d=ac[b],e=0;e<b;e+=2)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2]}else d=v.subarray(c>>2,c+b*8>>2);R.uniform2iv(X(a),d)}},Tb:(a,b,c)=>{if(W.version>=2)b&&R.uniform3fv(X(a),y,c>>2,b*3);else{if(b<=96){b*=3;for(var d=Y[b],e=0;e<b;e+=3)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+
4)>>2],d[e+2]=y[c+(4*e+8)>>2]}else d=y.subarray(c>>2,c+b*12>>2);R.uniform3fv(X(a),d)}},Pb:(a,b,c)=>{if(W.version>=2)b&&R.uniform3iv(X(a),v,c>>2,b*3);else{if(b<=96){b*=3;for(var d=ac[b],e=0;e<b;e+=3)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2]}else d=v.subarray(c>>2,c+b*12>>2);R.uniform3iv(X(a),d)}},Sb:(a,b,c)=>{if(W.version>=2)b&&R.uniform4fv(X(a),y,c>>2,b*4);else{if(b<=72){var d=Y[4*b],e=y;c>>=2;b*=4;for(var f=0;f<b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+
3]}}else d=y.subarray(c>>2,c+b*16>>2);R.uniform4fv(X(a),d)}},Ob:(a,b,c)=>{if(W.version>=2)b&&R.uniform4iv(X(a),v,c>>2,b*4);else{if(b<=72){b*=4;for(var d=ac[b],e=0;e<b;e+=4)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2],d[e+3]=v[c+(4*e+12)>>2]}else d=v.subarray(c>>2,c+b*16>>2);R.uniform4iv(X(a),d)}},Nb:(a,b,c,d)=>{if(W.version>=2)b&&R.uniformMatrix4fv(X(a),!!c,y,d>>2,b*16);else{if(b<=18){var e=Y[16*b],f=y;d>>=2;b*=16;for(var g=0;g<b;g+=16){var m=d+g;e[g]=f[m];e[g+1]=f[m+1];e[g+2]=f[m+
2];e[g+3]=f[m+3];e[g+4]=f[m+4];e[g+5]=f[m+5];e[g+6]=f[m+6];e[g+7]=f[m+7];e[g+8]=f[m+8];e[g+9]=f[m+9];e[g+10]=f[m+10];e[g+11]=f[m+11];e[g+12]=f[m+12];e[g+13]=f[m+13];e[g+14]=f[m+14];e[g+15]=f[m+15]}}else e=y.subarray(d>>2,d+b*64>>2);R.uniformMatrix4fv(X(a),!!c,e)}},n:a=>{a=T[a];R.useProgram(a);R.Nd=a},Xb:(a,b)=>{R.vertexAttribDivisor(a,b)},Yb:(a,b,c,d,e)=>{R.vertexAttribIPointer(a,b,c,d,e)},Zb:(a,b,c,d,e,f)=>{R.vertexAttribPointer(a,b,c,!!d,e,f)},fc:(a,b,c,d)=>R.viewport(a,b,c,d),pb:Ma,db:(a,b)=>cc(C.subarray(a,
a+b)),ub:function(){h.Dd=a=>{nc()!=0&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",h.Dd)},tb:function(){h.Id=a=>{var b=a.clipboardData.getData("text");ic(()=>{var c=ec(b);mc(c)})};window.addEventListener("paste",h.Id)},sb:function(){h.xe=[];h.Ed=b=>{b.stopPropagation();b.preventDefault()};h.Fd=b=>{b.stopPropagation();b.preventDefault()};h.Gd=b=>{b.stopPropagation();b.preventDefault()};h.Hd=b=>{b.stopPropagation();b.preventDefault();var c=b.dataTransfer.files;h.ye=
c;oc(c.length);for(let e=0;e<c.length;e++)ic(()=>{var f=ec(c[e].name);pc(e,f)});var d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);qc(b.clientX,b.clientY,d)};var a=h.Vc;a.addEventListener("dragenter",h.Ed,!1);a.addEventListener("dragleave",h.Fd,!1);a.addEventListener("dragover",h.Gd,!1);a.addEventListener("drop",h.Hd,!1)},mb:function(){var a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},nb:function(a){h.ed&&(URL.revokeObjectURL(h.ed[a].Ud),
h.ed[a]=null)},Ua:function(a,b){b!==0&&(document.title=b?I(C,b):"");a=a?I(C,a):"";h.canvas!==void 0&&(typeof h.canvas==="object"?ib[a]=h.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));h.Vc=L(a);h.Vc||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);h.Vc.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},ib:function(){window.removeEventListener("beforeunload",h.Dd)},hb:function(){window.removeEventListener("paste",
h.Id)},gb:function(){var a=h.Vc;a.removeEventListener("dragenter",h.Ed);a.removeEventListener("dragleave",h.Fd);a.removeEventListener("dragover",h.Gd);a.removeEventListener("drop",h.Hd)},q:function(){h.Vc&&h.Vc.requestPointerLock&&h.Vc.requestPointerLock()},ob:function(a,b,c){if(h.Vc){if(b===0)a="none";else if(c!=0)a=h.ed[a].Wd;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a=
"ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}h.Vc.style.cursor=a}},lb:function(a,b,c){var d=document.createElement("canvas");d.width=a;d.height=b;var e=d.getContext("2d"),f=e.createImageData(a,b);f.data.set(C.subarray(c,c+a*b*4));e.putImageData(f,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},$:function(a,
b){b=b?I(C,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}};function vc(a=[]){var b=lc;a.unshift(ba);var c=a.length,d=dc((c+1)*4),e=d,f;for(f of a)B[e>>2]=ec(f),e+=4;B[e>>2]=0;try{var g=b(c,d);ha=g;Ma(g)}catch(m){La(m)}}
function zc(a=aa){function b(){h.calledRun=!0;if(!p){Ac.uc();h.onRuntimeInitialized?.();h.noInitialRun||vc(a);if(h.postRun)for(typeof h.postRun=="function"&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();pa.push(c)}oa(pa)}}if(F>0)G=zc;else{if(h.preRun)for(typeof h.preRun=="function"&&(h.preRun=[h.preRun]);h.preRun.length;)ra();oa(qa);F>0?G=zc:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b()}}var Ac;
(async function(){function a(c){c=Ac=c.exports;lc=h._main=c.vc;h._oayao_set_days_counter_start_ms=c.wc;h._trigger_meteor_shower=c.xc;mc=h.__sapp_emsc_onpaste=c.yc;nc=h.__sapp_html5_get_ask_leave_site=c.zc;oc=h.__sapp_emsc_begin_drop=c.Ac;pc=h.__sapp_emsc_drop=c.Bc;qc=h.__sapp_emsc_end_drop=c.Cc;h.__sapp_emsc_invoke_fetch_cb=c.Dc;h.__sapp_emsc_set_fullscreen_flag=c.Ec;rc=c.Fc;wa=c.Gc;Fa=c.Hc;sc=c.Ic;Q=c.Jc;hc=c.Kc;dc=c.Lc;fc=c.Mc;tc=c.tc;lb=c.Nc;c=tc.buffer;x=new Int8Array(c);u=new Int16Array(c);C=
new Uint8Array(c);na=new Uint16Array(c);v=new Int32Array(c);B=new Uint32Array(c);y=new Float32Array(c);A=new Float64Array(c);w=new BigInt64Array(c);new BigUint64Array(c);F--;h.monitorRunDependencies?.(F);F==0&&G&&(c=G,G=null,c());return Ac}F++;h.monitorRunDependencies?.(F);var b={a:uc};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{c(a(d,e))})});ia??=h.locateFile?h.locateFile("oayao.wasm",da):da+"oayao.wasm";return function(c){return a(c.instance)}(await la(b))})();zc();
